### ISSUE TITLE
Device Status Now Returning "Water tank=False" Even When Full

### ISSUE THREAD

**Issue by java007md** [barban-dev/midea_inventor_dehumidifier#14]
For months, I have been able to check the tank status of the midea dehumidifier by returning the device status and looking for "Water tank=True" as the indicator that the tank needs to be manually emptied.

I have not received that status for over a week, even with the tank showing full. The official midea app does show the tank is full.

Has anyone else experienced this issue? I'm wondering if something changed on the remote side. There are no other indications of an issue with accessing the device, logging in, etc., at least that I have noticed.

Suggestions are welcome.

[update: 20220628]
I had one notification that the tank was full, but today the status returned is still showing "Water tank=False". Puzzling.

**Comment by matteocorti** [comment]
Same issue here

**Comment by barban-dev** [comment]
> [update: 20220628]
> I had one notification that the tank was full, but today the status returned is still showing "Water tank=False". Puzzling.

It was a issue from cloud side.
