### ISSUE TITLE
Failed to setup integration

### ISSUE THREAD

**Issue by jlm70** [barban-dev/midea_inventor_dehumidifier#15]
I just bought a new nice **Inventor Eva ION Pro Wifi 20L**, and installed the Midea integration via HACS.
I’m using an RPi4 with latest HA updates.
I updated my config file with user/pwd (in clear, at the moment) and restarted more times.
The dehumidifier works perfectly with its iOS app.

Unluckily I always get this error:

```
Setup failed for custom integration midea_dehumidifier: Integration failed to initialize.
01:34:16 – (ERROR) setup.py
midea-dehumi: login error
01:34:16 – (ERROR) midea_dehumidifier (custom integration)

```

Any idea about how to better address and solve the issue? 
Many thanks in advance

**Comment by barban-dev** [comment]
refer to [homeassistant-midea-dehumidifier](https://github.com/barban-dev/homeassistant-midea-dehumidifier/issues)
