### ISSUE TITLE
tank_show (full) attribute no longer working

### ISSUE THREAD

**Issue by mourmeer** [barban-dev/midea_inventor_dehumidifier#19]
i seems not to be albel to find the tank_show (when tank is full) entry.
It seems not working.
Disappeared after an update.

I have an automations running on it so I would liek to have it back.
I see it available in the files, but not as an attribute.

**Comment by strandaster** [comment]
I have the same issue (just wondering why my automation is not working anymore) and did some investigation. In the last release there were no changes which could affect that the tank attribute is not showing anymore. Maybe there is an issue in the underlaying libraries or the manufacturer did some changes on their API.
Maybe @barban-dev can shed some light on this and give us a hint how to get the attribute back again.

**Comment by barban-dev** [comment]
refer to [homeassistant-midea-dehumidifier](https://github.com/barban-dev/homeassistant-midea-dehumidifier/issues) issues
