### ISSUE TITLE
Always response 3176

### ISSUE THREAD

**Issue by Repsionu** [barban-dev/midea_inventor_dehumidifier#2]
At first kudos for Your great work on decrypting Midea API and writing this Python code. 
My problem is not really an issue with Your repository nor an error. I'm stuck in connecting to my device. NetHomePlus app works OK, but if I try to connect to API everything is OK at first- logs in, gets device ID and status(ON,  online, device name from cloud). But when I try to fetch data from cloud I get:

 Choose a command: 3
ERROR:root:MideaClient::send_api_request: errorCode=3176, errorMessage="The asyn
 reply does not exist "
ERROR:root:MideaClient::appliance_transparent_send: result=ERROR in API response
: result key not found
ERROR:root:MideaClient::get_device_status: invalid API response
=============================

And this problem persists with all my devices and Midea API access progs in Ruby and Python... 
Maybe You can hint me how to troubleshoot it further?
Regards, JR

**Comment by ronmichel** [comment]
Did you find any info on that? I am also stuck on that issue

**Comment by Repsionu** [comment]
Sorry, not yetRepsi kirjakasti P20 Pro-------- Originaalsõnum --------Teema: Re: [barban-dev/midea_inventor_dehumidifier] Always response 3176 (#2)Saatja: ronmichel Saaja: barban-dev/midea_inventor_dehumidifier Koopia: Repsionu ,Author Did you find any info on that? I am also stuck on that issue
