### ISSUE TITLE
I am unable to make it work in hass.io

### ISSUE THREAD

**Issue by mrobotto-dev** [barban-dev/midea_inventor_dehumidifier#8]
Does anyone can confirm that the custom component works?

It does not work for me:

> The following integrations and platforms could not be set up:
> 
> midea_dehumi
> Please check your config.

**Comment by pax2011** [comment]
Did tou solved this?

**Comment by mrobotto-dev** [comment]
Nope

Il ven 26 giu 2020, 16:10 pax2011 <notifications@github.com> ha scritto:

**Comment by barban-dev** [comment]
You can try the new custom component (platform) available [here.](https://github.com/barban-dev/homeassistant-midea-dehumidifier). It can work on Home Assistant version 0.96.0 or newer.
